port: 3000
bindIP: 0.0.0.0

db:
  type: postgres
  host: ep-odd-queen-ag68f36e-pooler.c-2.eu-central-1.aws.neon.tech
  port: 5432
  user: neondb_owner
  password: npg_p75cgGwkZAxo
  db: neondb
  ssl: true
  logging: false
  synchronize: false
  migrations:
    auto: false
    allowConsole: false

redis:
  host: localhost
  port: 6379
  password: null
  db: 0
  ssl: false

auth:
  audience: null
  tokenExpiration: 7d
  tokenRenewal: 1d

